version: '2.1'

services:
  oidcfed-minifed-docker:
    image: oidcfed-minifed-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 3000:3000
        - 8080:8080
        - 8100:8100
                
