version: '2.1'

services:
  oidcfed-minifed-docker:
    image: tehnari/oidcfed-minifed-docker
    deploy:
      restart_policy:
        condition: on-failure          
    build: .
    ports:
        - "8080:8080"
        - "8100:8100"