version: '2.1'

services:
  oidcfed-minifed-docker:
    image: tehnari/oidcfed-minifed-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8080:8080
        - 8100:8100

